clone:
  depth: full

definitions:
  services:
    docker:
      memory: 2048
  caches:
    sonar: ~/.sonar/cache
  steps:
  - step: &build-test-sonarcloud
      name: Build, test and analyze on SonarCloud
      image: golang:1.20
      caches:
        - sonar
      script:
        - set -xe
        - make run-test
        - make dbuild
        - pipe: sonarsource/sonarcloud-scan:1.4.0
          variables:
              SONAR_SCANNER_OPTS: -Xmx2048m
              EXTRA_ARGS: '-Dsonar.sources=. -Dsonar.exclusions=**/*_test.go,**/vendor/**,**/mocks/** -Dsonar.test.inclusions=**/*_test.go
-Dsonar.test.exclusions=**/vendor/**,**/*.pb.go,**/*.pb.gw.go,**/simulation/**,**/*.pulsar.go -Dsonar.go.coverage.reportPaths=coverage/coverage.out'
  - step: &check-quality-gate-sonarcloud
      name: Check the Quality Gate on SonarCloud
      script:
        - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

pipelines:
  branches:
    develop:
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
  pull-requests:
    '**':
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud