accounts:
  - name: validator
    coins: ["100000000000000000nshr", "100000000000cent"]
    mnemonic: "arrange amateur body cotton slim roof hand blush monkey remove expect rug hazard spoil flag choose tomato end duty nominee wheel cushion into stable"
  - name: authority
    coins: ["100000000000000000nshr", "100000000000cent"]
    mnemonic: "exile dutch volcano mosquito tree correct blame tape involve fiscal blossom emerge install grant normal divorce shiver barrel island drink local banana educate fix"
  - name: treasurer
    coins: ["100000000000000000nshr", "100000000000cent"]
    mnemonic: "hair bacon dirt torch air uphold tackle involve pool time token junior melody option judge thumb dance tube loud noise eternal congress fragile apart"
  - name: account-operator
    coins: ["100000000000000000nshr", "100000000000cent"]
    mnemonic: "pool mother column hurdle jealous wear host attack speak vague client demise inherit arrange lens purity time math decade renew south ring retreat balance"
  - name: idsigner
    coins: ["100000000000000000nshr", "100000000000cent"]
    mnemonic: "memory mind warfare pull risk math concert address zero speak glimpse outside economy hill boil boss pulp much connect install clip short object tobacco"
  - name: user
    coins: [ "100000000000nshr" ]
    mnemonic: "bright payment cash tomato tragic impulse perfect jacket matter jelly artist pulse will cinnamon erase middle elevator away clinic razor rotate tide unfair trigger"
  - name: approver
    coins: ["100000000000nshr"]
    mnemonic: "spend people immense ill property hungry craft corn quote once hand clarify adapt disorder airport balance alley wisdom physical appear debris awake pencil skate"
  - name: "relayer"
    coins: ["100000000000nshr"]
    mnemonic : "indoor donate grid ostrich tree swamp cactus common piano buzz version world second try garage squirrel alert fork december control bind spoon taste essay
"
validator:
  name: validator
  staked: "100000000000000000nshr"
client:
  openapi:
    path: "docs/static/openapi.yml"
build:
  binary: "shareledger"
  main: "./cmd/Shareledgerd"
# faucet:
#   name: bob
#   coins: ["5token", "100000stake"]
genesis:
  chain_id: "ShareRing-VoyagerNet"
  app_state:
    staking:
      params:
        bond_denom: "nshr"
    crisis:
      constant_fee:
        denom: "nshr"
    gov:
      deposit_params:
        min_deposit:
          - amount: "100000000"
            denom: "nshr"
    bank:
      denom_metadata:
        - description: "The native smallest token of shr chain"
          denom_units:
            - denom: nshr
              exponent: 0
              aliases:
                - nshr
            - denom: "shr"
              exponent: 9
              aliases:
                - shr
          base: "nshr"
          display: "shr"
          name: "nshr"
          symbol: "nshr"
    mint:
      minter:
        inflation: "0"
      params:
        mint_denom: "nshr"
        inflation_max: "0"
        inflation_min: "0"
    electoral:
      accStateList:
        - key: shrploadershareledger1lq9svs76xwekrrzw7uprekyqydf7fp02p8zp8e
          address: shareledger1lq9svs76xwekrrzw7uprekyqydf7fp02p8zp8e
          status: active
        - key: votershareledger18pf3zdwqjntd9wkvfcjvmdc7hua6c0q2eck5h5
          address: shareledger18pf3zdwqjntd9wkvfcjvmdc7hua6c0q2eck5h5
          status: active
        - key: approvershareledger1j4ndn4qed0ukulc0a6a5fxe6yxmnm7wh59pwpn
          address: shareledger1j4ndn4qed0ukulc0a6a5fxe6yxmnm7wh59pwpn
          status: active
        - key: relayershareledger16k53l0v5fr93u2kpe7ek2lc3tm37k4954zalvv
          address: shareledger16k53l0v5fr93u2kpe7ek2lc3tm37k4954zalvv
          status: active
      authority:
        address: shareledger1lq9svs76xwekrrzw7uprekyqydf7fp02p8zp8e
      treasurer:
        address: shareledger1l5hkf2epa5xmvngnjaasj5dp9jp7ut6s9mrqve
    interchainaccounts: #Default config for ibc
      host_genesis_state:
        active_channels: []
        interchain_accounts: []
        port: icahost
        params:
          host_enabled: false
          allow_messages: []
      controller_genesis_state:
        active_channels: []
        interchain_accounts: []
        params:
          controller_enabled: true
        ports: []
    swap:
      batchCount: '2'
      batchList:
        - id: '1'
          network: 'erc20'
          signature: >-
            0x6f62ea25cbf6d5f4a6829b6e671b769085300d8aac75f7574427fef8fc3d7fb8620818bb95d920fcd7f5a54fb0804d29b3bf0f3afdef0b507da4d729dcca932d1c
          status: pending
          txHash: ''
          txIds:
            - '1'
            - '2'
      formatList:
        - creator: shareledger1lq9svs76xwekrrzw7uprekyqydf7fp02p8zp8e
          network: erc20
          schema: >-
            {"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Swap":[{"name":"ids","type":"uint256[]"},{"name":"tos","type":"address[]"},{"name":"amounts","type":"uint256[]"}]},"primaryType":"Swap","domain":{"name":"ShareRingSwap","version":"2.0","chainId":"0x7a69","verifyingContract":"0x0165878a594ca255338adfa4d48449f69242eb8f","salt":""}}
      idList: [ ]
      params:
        outFee: out_fee
      requestCount: '3'
      requestList:
        - amount:
            amount: '10.000000000000000000'
            denom: shr
          batchId: '1'
          createdAt: '1652165972'
          destAddr: '0xfd98647ef698567357a8065849f0beb76812c8d7'
          destNetwork: erc20
          fee:
            amount: '2.000000000000000000'
            denom: shr
          id: '1'
          srcAddr: shareledger1t3g4570e23h96h5hm5gdtfrjprmvk9qwmrglfr
          srcNetwork: slp3
          status: approved
        - amount:
            amount: '10.000000000000000000'
            denom: shr
          batchId: '1'
          createdAt: '1652165978'
          destAddr: '0xfd98647ef698567357a8065849f0beb76812c8d9'
          destNetwork: erc20
          fee:
            amount: '2.000000000000000000'
            denom: shr
          id: '2'
          srcAddr: shareledger1t3g4570e23h96h5hm5gdtfrjprmvk9qwmrglfr
          srcNetwork: slp3
          status: approved
init:
  client:
    chain-id: "ShareRing-VoyagerNet"