version: 1
version: 1
build:
  main: ./cmd/Shareledgerd
  binary: shareledger
  proto:
    path: proto
    third_party_paths:
      - third_party/proto
      - proto_vendor
accounts:
  - name: validator
    coins:
      - 100000000000000000nshr
      - 100000000000cent
    mnemonic: arrange amateur body cotton slim roof hand blush monkey remove expect rug hazard spoil flag choose tomato end duty nominee wheel cushion into stable
  - name: authority
    coins:
      - 100000000000000000nshr
      - 100000000000cent
    mnemonic: work like grass pyramid august topic exit wood reunion until retire frown bean cherry stage attack shed oxygen chronic return kiss hint hat future
  - name: treasurer
    coins:
      - 100000000000000000nshr
      - 100000000000cent
    mnemonic: bird pizza tobacco omit cricket noodle hold wagon opinion shiver scout nature discover almost permit ceiling endless total sight cattle crisp calm popular flat
  - name: account-operator
    coins:
      - 100000000000000000nshr
      - 100000000000cent
    mnemonic: decline electric decade treat scissors floor fade fade exile swim destroy unusual noodle cabin toy print cover limb old report that balance pelican member
  - name: idsigner
    coins:
      - 100000000000000000nshr
      - 100000000000cent
    mnemonic: memory mind warfare pull risk math concert address zero speak glimpse outside economy hill boil boss pulp much connect install clip short object tobacco
  - name: user
    coins:
      - 1000000000000000nshr
    mnemonic: bright payment cash tomato tragic impulse perfect jacket matter jelly artist pulse will cinnamon erase middle elevator away clinic razor rotate tide unfair trigger
  - name: approver
    coins:
      - 100000000000nshr
    mnemonic: spend people immense ill property hungry craft corn quote once hand clarify adapt disorder airport balance alley wisdom physical appear debris awake pencil skate
  - name: relayer
    coins:
      - 100000000000nshr
    mnemonic: indoor donate grid ostrich tree swamp cactus common piano buzz version world second try garage squirrel alert fork december control bind spoon taste essay
  - name: swap_manager
    coins:
      - 100000000000nshr
    mnemonic: logic fade bike misery female father false speak code immune improve key food enter night timber kick spare amused miss expire bottom walk century
  - name: doc-issuer
    coins:
      - 100000000000nshr
    mnemonic: loyal siren evoke advice churn behave volcano wood ecology select unusual clock impulse angry scene protect lucky muffin chimney earth type provide taste volcano
faucet:
  name: null
  coins: []
  host: 0.0.0.0:4500
client:
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    bank:
      denom_metadata:
        - base: nshr
          denom_units:
            - aliases:
                - nshr
              denom: nshr
              exponent: 0
            - aliases:
                - shr
              denom: shr
              exponent: 9
          description: The native smallest token of shr chain
          display: shr
          name: nshr
          symbol: nshr
    crisis:
      constant_fee:
        denom: nshr
    electoral:
      accStateList:
        - address: shareledger1lq9svs76xwekrrzw7uprekyqydf7fp02p8zp8e
          key: shrploadershareledger1lq9svs76xwekrrzw7uprekyqydf7fp02p8zp8e
          status: active
        - address: shareledger18pf3zdwqjntd9wkvfcjvmdc7hua6c0q2eck5h5
          key: votershareledger18pf3zdwqjntd9wkvfcjvmdc7hua6c0q2eck5h5
          status: active
        - address: shareledger1j4ndn4qed0ukulc0a6a5fxe6yxmnm7wh59pwpn
          key: approvershareledger1j4ndn4qed0ukulc0a6a5fxe6yxmnm7wh59pwpn
          status: active
        - address: shareledger16k53l0v5fr93u2kpe7ek2lc3tm37k4954zalvv
          key: relayershareledger16k53l0v5fr93u2kpe7ek2lc3tm37k4954zalvv
          status: active
        - address: shareledger1yfwgejzj4nmkp6es6q3xea9uwexy5xwjs9rpcx
          key: swapManagershareledger1yfwgejzj4nmkp6es6q3xea9uwexy5xwjs9rpcx
          status: active
        - address: shareledger1mms7cehvyx7pxp7lllt0mn47hz5ufxwfwc2t95
          key: accopshareledger1mms7cehvyx7pxp7lllt0mn47hz5ufxwfwc2t95
          status: active
        - address: shareledger1qn7whj8v3gjf3a2nncydu88kt325xtd3t3gc95
          key: docIssuershareledger1qn7whj8v3gjf3a2nncydu88kt325xtd3t3gc95
          status: active
        - address: shareledger19up5qp0h3ffyhz3d5cnhhnlzjpgpn23ppt9yjk
          key: idsignershareledger19up5qp0h3ffyhz3d5cnhhnlzjpgpn23ppt9yjk
          status: active
      authority:
        address: shareledger19ac3d6cwqwpzvaxr4xv9kfduwtyswad88fjgw4
      treasurer:
        address: shareledger1hq7wjjgeymvs3q4vmkvac3dghfsjwvjvf8jdaw
    gov:
      deposit_params:
        min_deposit:
          - amount: "1"
            denom: nshr
      voting_params:
        voting_period: 100s
    interchainaccounts:
      controller_genesis_state:
        active_channels: []
        interchain_accounts: []
        params:
          controller_enabled: true
        ports: []
      host_genesis_state:
        active_channels: []
        interchain_accounts: []
        params:
          allow_messages: []
          host_enabled: false
        port: icahost
    mint:
      minter:
        inflation: "0"
      params:
        inflation_max: "0"
        inflation_min: "0"
        mint_denom: nshr
    staking:
      params:
        bond_denom: nshr
    swap:
      batchCount: "1"
      params: null
      requestCount: "1"
      requests: []
    distribution:
      params:
        community_tax: "0"
    distributionx:
      params:
        wasm_master_builder: "0.125"
        wasm_contract_admin: "0.125"
        wasm_development: "0.25"
        wasm_validator: "0.5"
        native_validator: "0.5"
        native_development: "0.5"
        builder_windows: 50
        tx_threshold: 2
        dev_pool_account: shareledger1t3g4570e23h96h5hm5gdtfrjprmvk9qwmrglfr
  chain_id: ShareRing-VoyagerNet
validators:
  - name: validator
    bonded: 100000000000000000nshr
    app:
      min_gas_prices: 1000nshr
      api:
        address: "tcp://0.0.0.0:1317"
      grpc:
        address: "0.0.0.0:9090"
      grpc-web:
        address: "0.0.0.0:9091"
    client:
      chain-id: ShareRing-VoyagerNet
      keyring-backend: test
      broadcast-mode: block
      node: "tcp://localhost:26657"
    config:
      rpc:
        laddr: "tcp://127.0.0.1:26657"
        pprof_laddr: "localhost:6060"
      p2p:
        laddr: "tcp://0.0.0.0:26656"
      proxy_app: "tcp://127.0.0.1:26658"
