accounts:
  - name: validator
    coins: ["100000000shr"]
  - name: authority
    coins: ["100000000shr"]
  - name: treasurer
    coins: ["100000000shr"]
  - name: account-operator
    coins: ["100000000shr"]
  - name: idsigner
    coins: ["100000000shr"]
validator:
  name: validator
  staked: "10000000shr"
client:
  openapi:
    path: "docs/static/openapi.yml"
# faucet:
#   name: bob
#   coins: ["5token", "100000stake"]
genesis:
  chain_id: "ShareRing-VoyagerNet"
  app_state:
    staking:
      params:
        bond_denom: "shr"