accounts:
  - name: validator
    coins: ["100000000shr", "1000000000shrp"]
  - name: authority
    coins: ["100000000shr", "1000000000shrp"]
  - name: treasurer
    coins: ["100000000shr", "1000000000shrp"]
  - name: account-operator
    coins: ["100000000shr", "1000000000shrp"]
  - name: idsigner
    coins: ["100000000shr", "1000000000shrp"]
  - name: alice
    coins: ["100000000shr", "1000000000shrp"]
  - name: bob
    coins: ["100000000shr", "1000000000shrp"]
validator:
  name: validator
  staked: "10000000shr"
client:
  openapi:
    path: "docs/static/openapi.yml"
build:
  binary: "shareledger"
# faucet:
#   name: bob
#   coins: ["5token", "100000stake"]
genesis:
  chain_id: "ShareRing-VoyagerNet"
  app_state:
    staking:
      params:
        bond_denom: "shr"
    crisis:
      constant_fee:
        denom: "shr"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "shr"
    mint:
      params:
        mint_denom: "shr"
init:
  client:
    chain-id: "ShareRing-VoyagerNet"
