version: '3'

services:
  shareledgernode0:
    container_name: shareledgernode0
    image: "shareledger/mynode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-shareledger.log}
    volumes:
      - ./build:/shareledger:Z
    networks:
      localnet:
        ipv4_address: 172.194.4.2

  shareledgernode1:
    container_name: shareledgernode1
    image: "shareledger/mynode"
    ports:
      - "26658-26659:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-shareledger.log}
    volumes:
      - ./build:/shareledger:Z
    networks:
      localnet:
        ipv4_address: 172.194.4.3

  shareledgernode2:
    container_name: shareledgernode2
    image: "shareledger/mynode"
    ports:
      - "26660-26661:26656-26657"
    environment:
      - ID=2
      - LOG=${LOG:-shareledger.log}
    volumes:
      - ./build:/shareledger:Z
    networks:
      localnet:
        ipv4_address: 172.194.4.4

  shareledgernode3:
    container_name: shareledgernode3
    image: "shareledger/mynode"
    ports:
      - "26662-26663:26656-26657"
    environment:
      - ID=3
      - LOG=${LOG:-shareledger.log}
    volumes:
      - ./build:/shareledger:Z
    networks:
      localnet:
        ipv4_address: 172.194.4.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.194.4.0/16
