version: '3'

services:
  nginx:
    container_name: snginx
    image: nginx:alpine
    restart: always
    depends_on:
      - snode0
      - snode2
    ports:
      - "1317-1318:1317-1318"
      - "26657-26658:26657-26658"
      - "9090-9091:9090-9091"
    volumes:
      - ./testnet/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./testnet/nginx/certs:/etc/nginx/certs
  snode0:
    container_name: snode0
    image: "sharering/shareledger:latest"
    restart: always
    hostname: snode0
    expose:
      - 26656
      - 26657
      - 9090
      - 9091
      - 1317
      - 26658
      - 26660
    volumes:
      - ./testnet/node0:/root/.Shareledger
      - ./testnet/script:/app/script:ro
    command:
      - shareledger
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE3ID}@${NODE3IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  snode1:
    container_name: snode1
    restart: always
    hostname: snode1
    image: "sharering/shareledger:latest"
    expose:
      - 26656
      - 26657
      - 9090
      - 9091
      - 1317
      - 26658
      - 26660
    volumes:
      - ./testnet/node1:/root/.Shareledger
    command:
      - shareledger
      - start
      - --p2p.persistent_peers
      - ${NODE0ID}@${NODE0IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE3ID}@${NODE3IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  snode2:
    container_name: snode2
    restart: always
    hostname: snode2
    image: "sharering/shareledger:latest"
    expose:
      - 26656
      - 26657
      - 9090
      - 9091
      - 1317
      - 26658
      - 26660
    volumes:
      - ./testnet/node2:/root/.Shareledger
    command:
      - shareledger
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE0ID}@${NODE0IP}:26656,${NODE3ID}@${NODE3IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  snode3:
    container_name: snode3
    image: "sharering/shareledger:latest"
    restart: always
    hostname: snode3
    expose:
      - 26656
      - 26657
      - 9090
      - 9091
      - 1317
      - 26658
      - 26660
    volumes:
      - ./testnet/node3:/root/.Shareledger
    command:
      - shareledger
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE0ID}@${NODE0IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  mongo:
    image: mongo:5.0.8
    container_name: mongo
    hostname: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - ./testnet/mongo/data/db:/data/db
      - ./testnet_config/script/mongoinit.sh:/docker-entrypoint-initdb.d/mongoinit.sh:ro
  relayer:
    container_name: relayer
    image: "sharering/shareledger:latest"
    restart: always
    hostname: relayer
    depends_on:
      - mongo
      - snode0
    volumes:
      - ./testnet/relayer:/root/.Shareledger
    command:
      - shareledger
      - relayer
      - start
      - --config
      - /root/.Shareledger/config.yml
      - --node
      - tcp://nginx:26657
      - --from
      - relayer