version: '3'

services:
  mongo:
    image: mongo:5.0.8
    container_name: mongo
    hostname: mongo
    networks:
      - proxyNetwork
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ShareRingiscaring!
    volumes:
      - ./testnet/mongo/data/db:/data/db
      - ./testnet_config/script/mongoinit.sh:/docker-entrypoint-initdb.d/mongoinit.sh:ro
  relayer:
    container_name: relayer
    image: "sharering/shareledger:latest"
    networks:
      - proxyNetwork
    restart: always
    hostname: relayer
    depends_on:
      - mongo
    entrypoint: ["/bin/sh","-c"]
    volumes:
      - ./testnet/relayer:/root/.Shareledger
      - ./testnet_config/script:/app/script:ro
    command:
      - |
        sh /app/script/setup_key.sh
        shareledger relayer start --config /root/.Shareledger/config.yml --node tcp://nginx:26657 --from relayer
networks:
  proxyNetwork:
    external:
      name: shareledgerNetwork