version: "3"

services:
  snode0:
    container_name: snode0
    image: "sharering/shareledger:latest"
    platform: linux/amd64
    restart: always
    networks:
      - proxynet
    hostname: snode0
    volumes:
      - ./testnet/node0:/root/.Shareledger
      - ./testnet/script:/app/script:ro
    command:
      - shareledger
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE3ID}@${NODE3IP}:26656,${NODE4ID}@${NODE4IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
      - --log_format
      - json
      - --log_level
      - info
      - --trace
  snode1:
    container_name: snode1
    restart: always
    hostname: snode1
    networks:
      - proxynet
    image: "sharering/shareledger:latest"
    platform: linux/amd64

    volumes:
      - ./testnet/node1:/root/.Shareledger
    command:
      - shareledger
      - start
      - --p2p.persistent_peers
      - ${NODE0ID}@${NODE0IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE3ID}@${NODE3IP}:26656,${NODE4ID}@${NODE4IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  snode2:
    container_name: snode2
    restart: always
    hostname: snode2
    networks:
      - proxynet
    image: "sharering/shareledger:latest"
    platform: linux/amd64

    volumes:
      - ./testnet/node2:/root/.Shareledger
    command:
      - shareledger
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE0ID}@${NODE0IP}:26656,${NODE3ID}@${NODE3IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  snode3:
    container_name: snode3
    image: "sharering/shareledger:latest"
    platform: linux/amd64
    restart: always
    hostname: snode3
    networks:
      - proxynet

    volumes:
      - ./testnet/node3:/root/.Shareledger
    command:
      - shareledger
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE0ID}@${NODE0IP}:26656,${NODE4ID}@${NODE4IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
  snode4:
    container_name: snode4
    image: "sharering/shareledger:latest"
    platform: linux/amd64
    restart: always
    hostname: snode4
    networks:
      - proxynet
    ports:
      - "1317-1318:1317-1318"
      - "26657-26658:26657-26658"
      - "9090-9091:9090-9091"
    volumes:
      - ./testnet/node4:/root/.Shareledger
    command:
      - shareledger
      - start
      - --p2p.persistent_peers
      - ${NODE1ID}@${NODE1IP}:26656,${NODE2ID}@${NODE2IP}:26656,${NODE0ID}@${NODE0IP}:26656,${NODE3ID}@${NODE3IP}:26656
      - --rpc.laddr
      - tcp://0.0.0.0:26657
networks:
  proxynet:
    name: shareledgerNetwork
