// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: shareledger/sdistribution/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	WasmMasterBuilder github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=wasm_master_builder,json=wasmMasterBuilder,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"wasm_master_builder"`
	WasmContractAdmin github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=wasm_contract_admin,json=wasmContractAdmin,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"wasm_contract_admin"`
	WasmDevelopment   github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=wasm_development,json=wasmDevelopment,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"wasm_development"`
	WasmValidator     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=wasm_validator,json=wasmValidator,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"wasm_validator"`
	NativeValidator   github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=native_validator,json=nativeValidator,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"native_validator"`
	NativeDevelopment github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=native_development,json=nativeDevelopment,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"native_development"`
	BuilderWindows    uint32                                 `protobuf:"varint,7,opt,name=builder_windows,json=builderWindows,proto3" json:"builder_windows,omitempty" yaml:"builder_windows"`
	TxThreshold       uint32                                 `protobuf:"varint,8,opt,name=tx_threshold,json=txThreshold,proto3" json:"tx_threshold,omitempty" yaml:"tx_threshold"`
	DevPoolAccount    string                                 `protobuf:"bytes,9,opt,name=dev_pool_account,json=devPoolAccount,proto3" json:"dev_pool_account,omitempty" yaml:"dev_pool_account"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdcf60c88e4ba53b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBuilderWindows() uint32 {
	if m != nil {
		return m.BuilderWindows
	}
	return 0
}

func (m *Params) GetTxThreshold() uint32 {
	if m != nil {
		return m.TxThreshold
	}
	return 0
}

func (m *Params) GetDevPoolAccount() string {
	if m != nil {
		return m.DevPoolAccount
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "sharering.shareledger.sdistribution.Params")
}

func init() {
	proto.RegisterFile("shareledger/sdistribution/params.proto", fileDescriptor_cdcf60c88e4ba53b)
}

var fileDescriptor_cdcf60c88e4ba53b = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x80, 0x13, 0x18, 0x85, 0x19, 0xd6, 0x8d, 0x0c, 0xb1, 0x50, 0xa4, 0x64, 0x0a, 0xd2, 0xb4,
	0xcb, 0x92, 0x03, 0x12, 0x87, 0x8a, 0xcb, 0xba, 0x72, 0x44, 0xaa, 0x2a, 0x04, 0x12, 0x97, 0xc8,
	0x8d, 0xad, 0xd4, 0x5a, 0x92, 0x17, 0xd9, 0x6e, 0xda, 0xfd, 0x0b, 0x8e, 0x1c, 0xf9, 0x11, 0xfc,
	0x88, 0x1d, 0x27, 0x0e, 0x08, 0x71, 0x88, 0x50, 0xfb, 0x0f, 0xfa, 0x0b, 0x50, 0xec, 0x6c, 0xcd,
	0x7a, 0xce, 0x29, 0xf1, 0xcb, 0x7b, 0xdf, 0xa7, 0xf7, 0x62, 0x1b, 0x9d, 0x88, 0x29, 0xe6, 0x34,
	0xa1, 0x24, 0xa6, 0x3c, 0x10, 0x84, 0x09, 0xc9, 0xd9, 0x64, 0x26, 0x19, 0x64, 0x41, 0x8e, 0x39,
	0x4e, 0x85, 0x9f, 0x73, 0x90, 0x60, 0xbd, 0x51, 0x79, 0x9c, 0x65, 0xb1, 0xdf, 0xa8, 0xf0, 0xef,
	0x55, 0xf4, 0x5e, 0x45, 0x20, 0x52, 0x10, 0xa1, 0x2a, 0x09, 0xf4, 0x42, 0xd7, 0xf7, 0x5e, 0xc4,
	0x10, 0x83, 0x8e, 0x57, 0x6f, 0x3a, 0xea, 0xfd, 0xee, 0xa0, 0xce, 0x48, 0x69, 0xac, 0x04, 0x1d,
	0xce, 0xb1, 0x48, 0xc3, 0x14, 0x0b, 0x49, 0x79, 0x38, 0x99, 0xb1, 0x84, 0x50, 0x6e, 0x9b, 0xc7,
	0xe6, 0xe9, 0xee, 0xe0, 0xfd, 0x75, 0xe9, 0x1a, 0x7f, 0x4b, 0xf7, 0x24, 0x66, 0x72, 0x3a, 0x9b,
	0xf8, 0x11, 0xa4, 0x35, 0xbe, 0x7e, 0x9c, 0x09, 0x72, 0x19, 0xc8, 0xab, 0x9c, 0x0a, 0x7f, 0x48,
	0xa3, 0x5f, 0x3f, 0xcf, 0x50, 0x6d, 0x1f, 0xd2, 0x68, 0xfc, 0xbc, 0x02, 0x7f, 0x54, 0xdc, 0x81,
	0xc6, 0xde, 0xd9, 0x22, 0xc8, 0x24, 0xc7, 0x91, 0x0c, 0x31, 0x49, 0x59, 0x66, 0x3f, 0x68, 0xcb,
	0x76, 0x51, 0x73, 0xcf, 0x2b, 0xac, 0x15, 0xa3, 0x03, 0x65, 0x23, 0xb4, 0xa0, 0x09, 0xe4, 0x29,
	0xcd, 0xa4, 0xfd, 0xb0, 0x05, 0xd5, 0x7e, 0x45, 0x1d, 0x6e, 0xa0, 0x56, 0x84, 0xba, 0x4a, 0x54,
	0xe0, 0x84, 0x11, 0x2c, 0x81, 0xdb, 0x3b, 0x2d, 0x68, 0xf6, 0x2a, 0xe6, 0xe7, 0x5b, 0x64, 0xd5,
	0x4d, 0x86, 0x25, 0x2b, 0x68, 0x43, 0xf3, 0xa8, 0x8d, 0x6e, 0x34, 0x75, 0x23, 0xba, 0x44, 0x56,
	0x2d, 0x6a, 0x0e, 0xae, 0xd3, 0xc6, 0x3f, 0xd2, 0xdc, 0xe6, 0xe8, 0x2e, 0xd0, 0x7e, 0xbd, 0xe7,
	0xc2, 0x39, 0xcb, 0x08, 0xcc, 0x85, 0xfd, 0xf8, 0xd8, 0x3c, 0xdd, 0x1b, 0xf4, 0xd6, 0xa5, 0xfb,
	0xf2, 0x0a, 0xa7, 0x49, 0xdf, 0xdb, 0x4a, 0xf0, 0xc6, 0xdd, 0x3a, 0xf2, 0x45, 0x07, 0xac, 0x3e,
	0x7a, 0x26, 0x17, 0xa1, 0x9c, 0x72, 0x2a, 0xa6, 0x90, 0x10, 0xfb, 0x89, 0x22, 0x1c, 0xad, 0x4b,
	0xf7, 0x50, 0x13, 0x9a, 0x5f, 0xbd, 0xf1, 0x53, 0xb9, 0xf8, 0x74, 0xbb, 0xb2, 0x3e, 0xa0, 0x03,
	0x42, 0x8b, 0x30, 0x07, 0x48, 0x42, 0x1c, 0x45, 0x30, 0xcb, 0xa4, 0xbd, 0xab, 0x7a, 0x7d, 0xbd,
	0x2e, 0xdd, 0x23, 0x5d, 0xbf, 0x9d, 0xe1, 0x8d, 0xbb, 0x84, 0x16, 0x23, 0x80, 0xe4, 0x5c, 0x07,
	0xfa, 0x3b, 0xdf, 0x7f, 0xb8, 0xc6, 0x60, 0x74, 0xbd, 0x74, 0xcc, 0x9b, 0xa5, 0x63, 0xfe, 0x5b,
	0x3a, 0xe6, 0xb7, 0x95, 0x63, 0xdc, 0xac, 0x1c, 0xe3, 0xcf, 0xca, 0x31, 0xbe, 0xbe, 0x6b, 0x0c,
	0xec, 0xee, 0x4c, 0x07, 0xcd, 0x5b, 0x60, 0xb1, 0x75, 0x0f, 0xa8, 0x21, 0x4e, 0x3a, 0xea, 0xc4,
	0xbe, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x15, 0xed, 0x45, 0x31, 0x04, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DevPoolAccount) > 0 {
		i -= len(m.DevPoolAccount)
		copy(dAtA[i:], m.DevPoolAccount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DevPoolAccount)))
		i--
		dAtA[i] = 0x4a
	}
	if m.TxThreshold != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TxThreshold))
		i--
		dAtA[i] = 0x40
	}
	if m.BuilderWindows != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BuilderWindows))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.NativeDevelopment.Size()
		i -= size
		if _, err := m.NativeDevelopment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.NativeValidator.Size()
		i -= size
		if _, err := m.NativeValidator.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.WasmValidator.Size()
		i -= size
		if _, err := m.WasmValidator.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.WasmDevelopment.Size()
		i -= size
		if _, err := m.WasmDevelopment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.WasmContractAdmin.Size()
		i -= size
		if _, err := m.WasmContractAdmin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.WasmMasterBuilder.Size()
		i -= size
		if _, err := m.WasmMasterBuilder.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.WasmMasterBuilder.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.WasmContractAdmin.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.WasmDevelopment.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.WasmValidator.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.NativeValidator.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.NativeDevelopment.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.BuilderWindows != 0 {
		n += 1 + sovParams(uint64(m.BuilderWindows))
	}
	if m.TxThreshold != 0 {
		n += 1 + sovParams(uint64(m.TxThreshold))
	}
	l = len(m.DevPoolAccount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmMasterBuilder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WasmMasterBuilder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmContractAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WasmContractAdmin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmDevelopment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WasmDevelopment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WasmValidator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WasmValidator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeValidator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NativeValidator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NativeDevelopment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NativeDevelopment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuilderWindows", wireType)
			}
			m.BuilderWindows = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BuilderWindows |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxThreshold", wireType)
			}
			m.TxThreshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxThreshold |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DevPoolAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DevPoolAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
