mongoURI: mongodb+srv://phuong:uIoqBJDBzHn17Khe@cluster0.ol2f7.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
dbName: "ShareRing"
collectionName: "Request"
scanInterval: 15s
type: out
networks:
  erc20:
    signer: acc3
    url: https://ropsten.infura.io/v3/bf1a5b4c59cb45ea8ebf48497d3295ae
    exponent: 2
    chainId: 3
    swapContract: 0x1214696C8A2E207B05019493b10343CFc4e3D231 #swapContract
    pegWallet: 0x0362fBA2BdA9Bd05f53d6C8CC72257919899A9Ac #tokenContract
    lastScannedTransferEventBlockNumber: 0
    lastScannedSwapEventBlockNumber: 0
    swapTopic: 0x796a6fb73c9c09afe863a5d1bc7040da846e5aeb2ad3cb42ee36e08a0c0a3e71
    transferTopic: 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
    retry:
      intervalRetry: 10s
      maxRetry: 3
      retryPercentage: 10