mongoURI: mongodb+srv://phuong:uIoqBJDBzHn17Khe@cluster0.ol2f7.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
dbName: "ShareRing"
collectionName: "Request"
scanInterval: 5s
type: out
networks:
  erc20:
    signer: acc3
    url: https://eth-ropsten.alchemyapi.io/v2/0M8yP6-iyIof8dFJN0Jph59jJlSKqmbW
    chainId: 3
    contract: 0xecf82F815DB77182dD46195B46E6aB3BdB6F6977